\" -*- nroff -*-

\" v120 config utility
\"
\" This program is free software; you can redistribute it and/or modify
\" it under the terms of the GNU General Public License as published by
\" the Free Software Foundation; either version 2 of the License, or (at
\" your option) any later version.
\"
\" This program is distributed in the hope that it will be useful, but
\" WITHOUT ANY WARRANTY; without even the implied warranty of
\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
\" General Public License for more details.
\"
\" You should have received a copy of the GNU General Public License
\" along with this program. If not, see <http://www.gnu.org/licenses/>.
\"
\" Author: Dean W. Anneser
\" Company: RTLinux Solutions LLC for Highland Technology, Inc.
\" Date: 30 Apr 2021

.TH v120_config 1 "v120 configuration utility"

.SH NAME
.nf
\f4v120_config\f1 - read a VME configuration file, configure memory regions, probe for cards, write VME configuration output file
.fi

.SH SYNOPSIS
.nf
\f4v120_config\f1 \f4-i \f2input.conf\f1 \f4-o \f2output.conf\f1 [\f4-q\f1] [\f4-debug\f1] [\f4-scan\f1 [\f2all\f1|\f2a16\f1|\f2a24\f1|\f2a32\f1|\f2a16a24\f1]] [\f4-help\f1 [\f2repeater\f1|\f2vmedevice\f1]
.fi

.SH DESCRIPTION
The \f4v120_config\f1 utility is designed to configure the user defined A16/A24/A32 address spaces, and probe for user defined
VME devices listed in the \f2input.conf\f1 file, and write an \f2output.conf\f1 file containing the results of the VME probe.
Alternatively the \f2input.conf\f1 file need only define the address space attributes for the V120's in the system, and the
\f4v120_config\f1 will autoscan for the VME cards.  Presently, only up to one address region per type and a maximum of four
V120's per system is supported. 

.SH OPTIONS
.TP
\f4-help\f1
.br
prints out a terse option and argument list and definition.
.TP
\f4-help \f2repeater\f1
.br
prints out the options and arguments for V120 entries in \f2input.conf\f1.
.TP
\f4-help \f2vmedevice\f1
.br
prints out the options and arguments for VME device entries in \f2input.conf\f1.
.TP
\f4-i \f2input.conf\f1
.br
specifies the name of the V120/VME input configuration file (default name is: \f2input.conf\f1).
.TP
\f4-o \f2output.conf\f1
.br
specifies the name of the V120/VME output configuration file (default name is: \f2output.conf\f1).  This file contains the
results of the VME probe or autoscan. 
.TP
\f4-q\f1
.br
sets quiet flag.
.TP
\f4-debug\f1
.br
sets debug flag.
.TP
\f4-scan\f1 [\f2all\f1|\f2a16\f1|\f2a24\f1|\f2a32\f1|\f2a16a24\f1]
.br
this option can only be used if the \f2input.conf\f1 does not contain any VME board definitions.  The \f4-scan\f1 option by
itself is synonymous with \f4-scan\ \f2all\f1.  The \f4-scan\f1 option allows one to scan for VME boards in A16 space, or A24
space, or A32 space, or A16 and A24 space.  The \f2all\f1 option will scan for VME boards in all the A16/A24/A32 spaces.
Presently the Highland Technology devices listed below can be autoscanned:

.nf
.in +5
\f2v210\f1 -- VME Relay Module
\f2v220\f1 -- VME 4-20mA Analog Control I/O Module
\f2v230\f1 -- VME Analog Input Module
\f2v250\f1 -- VME Digital I/O Module
\f2v340\f1 -- VME Waveform Generator Module
\f2v344\f1 -- VME Waveform Generator
\f2v346\f1 -- VME Waveform Generator
\f2v350\f1 -- VME Analog/Digital Function Generator
\f2v360\f1 -- VME Tachometer Module
\f2v365\f1 -- VME Tachometer / Overspeed Module
\f2v370\f1 -- VME Waveform Generator
\f2v375\f1 -- VME Waveform Generator
\f2v380\f1 -- VME Strain Gauge / Weighing Module
\f2v385\f1 -- VME Strain Gauge / Load Cell Module
\f2v410\f1 -- VME RTD / Resistance Input Module
\f2v420\f1 -- VME Isolated Resistance Simulator
\f2v450\f1 -- VME Analog Input Module
\f2v460\f1 -- VME Analog Scanner Module
\f2v470\f1 -- VME Analog Output and Thermocouple Simulator Module
\f2v490\f1 -- VME Multi-range Digitizer
\f2v545\f1 -- VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
.in -5
.fi


.SH DEVICE TYPES
.SS repeater
.TP
\f4repeater \f2v120[\f1repeater_num\f2]\f1
.br
\f4repeater_num\f1 can range between 0-3.
.TP
\f4-a16 \f2vme_address\f1
.br
specifies (in hex) the base address for the A16 region 
.TP
\f4-s16 \f2size\f1
.br
specifies the size of the A16 region
.TP
\f4-S16 \f2SLOW\f1|\f2MED\f1|\f2FAST\f1|\f2MAX\f1 (optional)
.br
specifies VME speed of this region.  Default is \f2MAX\f1.
.TP
\f4-a24 \f2vme_address\f1
.br
specifies (in hex) the base address for the A24 region 
.TP
\f4-s24 \f2size\f1
.br
specifies the size of the A24 region
.TP
\f4-S24 \f2SLOW\f1|\f2MED\f1|\f2FAST\f1|\f2MAX\f1 (optional)
.br
specifies VME speed of this region.  Default is \f2MAX\f1.
.TP
\f4-a32 \f2vme_address\f1
.br
specifies (in hex) the base address for the A32 region 
.TP
\f4-s32 \f2size\f1
.br
specifies the size of the A32 region
.TP
\f4-S32 \f2SLOW\f1|\f2MED\f1|\f2FAST\f1|\f2MAX\f1 (optional)
.br
specifies VME speed of this region.  Default is \f2MAX\f1.

.SS vmedevice
.TP
\f4vmedevice \f2v450[\f1repeater_num\f2][\f1board_num\f2]\f1
.br
where \f4board_num\f1 is unique for a board type within a specific \f4repeater_num\f1 chassis.
.TP
\f4-base \f2vme_address\f1
.br
is the base address of the VME module.

.SH EXAMPLES
.SS Single V120 example
In a small test setup, where there is one VME chassis, and one V120 repeater, and three VME boards, the \f2input.conf\f1 file
may contain the following.  Note: lines starting with a '#' are ignored.  Also "sizes" may use 'k', 'K', 'm', or 'M' to specify
kilo or mega.  The bracketed integer after \f4repeater\ \f2v120\f1 specifies the repeater/controller/crate/chassis number.
Board specifications include the crate number and board number as \f2device_name[\f1crate_num\f2][\f1board_num\f2]\f1.  Board
numbers are unique across board types within the same chassis.   

.nf
.in +5
# -*- conf -*-  for emacs users
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f264k \f4-a24 \f20xff000000 \f4-s24 \f21m \f4-a32 \f20xe0000000 \f4-s32 \f22M\f1
# vmedevice board[repeater_num][board_num] -base board_base_address
\f4vmedevice \f2v545[\f10\f2][\f10\f2] \f4-base \f20xffff0000\f1
\f4vmedevice \f2v545[\f10\f2][\f11\f2] \f4-base \f20xffff1000\f1		# card listed but does not exist
\f4vmedevice \f2v545[\f10\f2][\f12\f2] \f4-base \f20xffff1800\f1		# card listed but does not exist
\f4vmedevice \f2v470[\f10\f2][\f10\f2] \f4-base \f20xffff0800\f1
\f4vmedevice \f2v450[\f10\f2][\f10\f2] \f4-base \f20xffff0a00\f1
\f4vmedevice \f2v375[\f10\f2][\f10\f2] \f4-base \f20xffff0c00\f1
.in -5
.fi

Run the v120_config utility:

.nf
.in +5
\f4v120_config -i \f2input.conf\f1 \f4-o \f2output.conf\f1
.in -5
.fi

Below is the contents of \f2output.conf\f1.  The \f4-o\f1 option is the online flag, followed by \f2true\f1 or \f2false\f1.  On
the \f4repeater\f1 line, the start for eash region are specified with \f4-sp16\f1, \f4-sp24\f1, and \f4-sp32\f1.  The end pages
are specified as \f4-ep16\f1, \f4-ep24\f1, and \f4ep32\f1.  

.nf
.in +5
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f20x10000 \f4-sp16 \f2264 \f4-ep16 \f2267 \f4-a24 \f20xff000000 \f4-s24 \f20x100000 \f4-sp24 \f2200 \f4-ep24 \f2263 \f4-a32 \f20xe0000000 \f4-s32 \f20x200000 \f4-sp32 \f272 \f4-ep32 \f2199 \f4-o \f4true\f1
\f4vmedevice \f2v545[\f10\f2][\f10\f2] \f4-base \f20xffff0000 \f4-a \f216 \f4-o \f2true\f1  # VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v545[\f10\f2][\f11\f2] \f4-base \f20xffff1000 \f4-a \f216 \f4-o \f2false\f1 # VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v545[\f10\f2][\f12\f2] \f4-base \f20xffff1800 \f4-a \f216 \f4-o \f2false\f1 # VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v470[\f10\f2][\f10\f2] \f4-base \f20xffff0800 \f4-a \f216 \f4-o \f2true\f1  # VME Analog Output and Thermocouple Simulator Module
\f4vmedevice \f2v450[\f10\f2][\f10\f2] \f4-base \f20xffff0a00 \f4-a \f216 \f4-o \f2true\f1  # VME Analog Input and Thermocouple Measurement Module
\f4vmedevice \f2v375[\f10\f2][\f10\f2] \f4-base \f20xffff0c00 \f4-a \f216 \f4-o \f2true\f1  # VME Arbitrary Waveform Generator
.in -5
.fi

.SS Double V120 example
In a small test setup, where only the first of two V120's are present, a \f2input.conf\f1 file may contain the following.

.nf
.in +5
# -*- conf -*-  for emacs users
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f264k \f4-a24 \f20xff000000 \f4-s24 \f21m \f4-a32 \f20xe0000000 \f4-s32 \f22M\f1
# vmedevice board[repeater_num][board_num] -base board_base_address
\f4vmedevice \f2v545[\f10\f2][\f10\f2] \f4-base \f20xffff0000\f1
\f4vmedevice \f2v545[\f10\f2][\f11\f2] \f4-base \f20xffff1000\f1		# card listed but does not exist
\f4vmedevice \f2v545[\f10\f2][\f12\f2] \f4-base \f20xffff1800\f1		# card listed but does not exist
\f4vmedevice \f2v470[\f10\f2][\f10\f2] \f4-base \f20xffff0800\f1
\f4vmedevice \f2v450[\f10\f2][\f10\f2] \f4-base \f20xffff0a00\f1
\f4vmedevice \f2v375[\f10\f2][\f10\f2] \f4-base \f20xffff0c00\f1

\f4repeater \f2v120[\f11\f2] \f4-a16 \f20xffff0000 \f4-s16 \f264k \f4-a24 \f20xff100000 \f4-s24 \f21m \f4-a32 \f20xe0200000 \f4-s32 \f22M\f1
# vmedevice board[repeater_num][board_num] -base board_base_address
\f4vmedevice \f2v545[\f11\f2][\f10\f2] \f4-base \f20xffff0000\f1
\f4vmedevice \f2v545[\f11\f2][\f11\f2] \f4-base \f20xffff1000\f1
\f4vmedevice \f2v545[\f11\f2][\f12\f2] \f4-base \f20xffff1800\f1
\f4vmedevice \f2v470[\f11\f2][\f10\f2] \f4-base \f20xffff0800\f1
\f4vmedevice \f2v450[\f11\f2][\f10\f2] \f4-base \f20xffff0a00\f1
\f4vmedevice \f2v375[\f11\f2][\f10\f2] \f4-base \f20xffff0c00\f1

.in -5
.fi

Run the V120_config utility:

.nf
.in +5
\f4v120_config -i \f2input.conf\f1 \f4-o \f2output.conf\f1
.in -5
.fi

The first V120 probes as being online, whereas the second does not.

.nf
.in +5
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f20x10000 \f4-sp16 \f2264 \f4-ep16 \f2267 \f4-a24 \f20xff000000 \f4-s24 \f20x100000 \f4-sp24 \f2200 \f4-ep24 \f2263 \f4-a32 \f20xe0000000 \f4-s32 \f20x200000 \f4-sp32 \f272 \f4-ep32 \f2199 \f4-o \f2true\f1
\f4vmedevice \f2v545[\f10\f2][\f10\f2] \f4-base \f20xffff0000 \f4-a \f216 \f4-o \f2true	\f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v470[\f10\f2][\f10\f2] \f4-base \f20xffff0800 \f4-a \f216 \f4-o \f2true	\f1# VME Analog Output and Thermocouple Simulator Module
\f4vmedevice \f2v450[\f10\f2][\f10\f2] \f4-base \f20xffff0a00 \f4-a \f216 \f4-o \f2true	\f1# VME Analog Input and Thermocouple Simulator Module
\f4vmedevice \f2v545[\f10\f2][\f11\f2] \f4-base \f20xffff1000 \f4-a \f216 \f4-o \f2false\f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v545[\f10\f2][\f12\f2] \f4-base \f20xffff1800 \f4-a \f216 \f4-o \f2false\f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v375[\f10\f2][\f10\f2] \f4-base \f20xffff0c00 \f4-a \f216 \f4-o \f2true \f1# VME Arbitrary Waveform Generator
\f4repeater \f2v120[\f11\f2] \f4-a16 \f20xffff8000 \f4-s16 \f20x10000 \f4-a24 \f20xff100000 \f4-s24 \f20x100000 \f4-a32 \f20xe0200000 \f4-s32 \f20x200000 \f4-o \f2false\f1
\f4vmedevice \f2v545[\f11\f2][\f10\f2] \f4-base \f20xffff0000 \f4-a \f20 \f4-o \f2false \f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v470[\f11\f2][\f10\f2] \f4-base \f20xffff0800 \f4-a \f20 \f4-o \f2false \f1# VME Analog Output and Thermocouple Simulator Module
\f4vmedevice \f2v450[\f11\f2][\f10\f2] \f4-base \f20xffff0a00 \f4-a \f20 \f4-o \f2false \f1# VME Analog Input and Thermocouple Simulator Module
\f4vmedevice \f2v545[\f11\f2][\f11\f2] \f4-base \f20xffff1000 \f4-a \f20 \f4-o \f2false	\f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v545[\f11\f2][\f12\f2] \f4-base \f20xffff1800 \f4-a \f20 \f4-o \f2false	\f1# VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v375[\f11\f2][\f10\f2] \f4-base \f20xffff0c00 \f4-a \f216 \f4-o \f2true \f1# VME Arbitrary Waveform Generator
.in -5
.fi

.SS Autoscan example
When using the autoscan function of \f4v120_config\f1, there cannot be any VME devices listed in \f2input.conf\f1.

.nf
.in +5
# -*- conf -*-  for emacs users
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f264k \f4-a24 \f20xff000000 \f4-s24 \f21m \f4-a32 \f20xe0000000 \f4-s32 \f22M\f1
\f4repeater \f2v120[\f11\f2] \f4-a16 \f20xffff0000 \f4-s16 \f264k \f4-a24 \f20xff100000 \f4-s24 \f21m \f4-a32 \f20xe0200000 \f4-s32 \f22M\f1
.in -5
.fi

Run the V120_config utility:

.nf
.in +5
\f4v120_config -i \f2input.conf\f1 \f4-o \f2output.conf\f1 \f4-scan \f2a16\f1
.in -5
.fi

Both V120's are listed, with card 0 being online, and card 1 being offline.  Only the cards probed in the address space specified will be listed.

.nf
.in +5
\f4repeater \f2v120[\f10\f2] \f4-a16 \f20xffff0000 \f4-s16 \f20x10000 \f4-sp16 \f2264 \f4-ep16 \f2267 \f4-a24 \f20xff000000 \f4-s24 \f20x100000 \f4-sp24 \f2200 \f4-ep24 \f2263 \f4-a32 \f20xe0000000 \f4-s32 \f20x200000 \f4-sp32 \f272 \f4-ep32 \f2199 \f4-o \f2true\f1
\f4repeater \f2v120[\f11\f2] \f4-a16 \f20xffff0000 \f4-s16 \f20x10000 \f4-a24 \f20xff100000 \f4-s24 \f20x100000 \f4-a32 \f20xe0200000 \f4-s32 \f20x200000 \f4-o \f2false\f1
\f4vmedevice \f2v545[\f10\f2][\f10\f2] \f4-base \f20xffff0000 \f4-a \f216 \f4-o \f2true\f1 # VME Synchro/Resolver/LVDT/RVDT Simulation/Acquisition Module
\f4vmedevice \f2v470[\f10\f2][\f10\f2] \f4-base \f20xffff0800 \f4-a \f216 \f4-o \f2true\f1 # VME Analog Output and Thermocouple Simulator Module
\f4vmedevice \f2v450[\f10\f2][\f10\f2] \f4-base \f20xffff0a00 \f4-a \f216 \f4-o \f2true\f1 # VME Analog Input Module
\f4vmedevice \f2v375[\f10\f2][\f10\f2] \f4-base \f20xffff0c00 \f4-a \f216 \f4-o \f2true\f1 # VME Arbitrary Waveform Generator
.in -5
.fi

.SH ERRORS
none

.SH VENDOR MANUAL
.nf
http://www.highlandtechnology.com/DSS/V120DS.shtml
.fi

.SH SEE ALSO
\f4get_vaddr_for_device(3)\f1

.SH CAVEATS
none

.SH RESTRICTIONS
none

.SH AUTHORS
Dean W. Anneser
